language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pfalzer/docker-practice -f Dockerfile.dev .
  
script:
  - docker run -e CI=true pfalzer/docker-practice npm run test -- --coverage